// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatpb/chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessage struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_41cf34dba7f8bdf6, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ChatMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatMessage) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "chat.ChatMessage")
}

func init() { proto.RegisterFile("chatpb/chat.proto", fileDescriptor_41cf34dba7f8bdf6) }

var fileDescriptor_41cf34dba7f8bdf6 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0x48, 0x2c,
	0x29, 0x48, 0xd2, 0x07, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x94,
	0x7c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x2c, 0xa9, 0x34, 0x4d, 0xbf, 0x24, 0x33,
	0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x00, 0xa2, 0x4c, 0x29, 0x9d, 0x8b, 0xdb, 0x39, 0x23, 0xb1,
	0xc4, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0xb5, 0xa2, 0x44,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60,
	0x52, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0x32, 0xe1, 0x62, 0x4f, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x4d, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0xd8, 0xa2, 0x07,
	0xb3, 0x45, 0x2f, 0x04, 0x66, 0x4b, 0x10, 0x4c, 0xa9, 0x91, 0x13, 0xc4, 0x22, 0xd7, 0x8a, 0xc4,
	0xdc, 0x82, 0x9c, 0x54, 0x21, 0x63, 0x2e, 0xee, 0xe2, 0xd4, 0xbc, 0x14, 0x98, 0xbd, 0x82, 0x7a,
	0x60, 0xa7, 0x23, 0x39, 0x45, 0x0a, 0x53, 0xc8, 0x89, 0x2d, 0x0a, 0xec, 0xab, 0x24, 0x36, 0xb0,
	0x45, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xc6, 0xcd, 0x7f, 0xf7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatExampleClient is the client API for ChatExample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatExampleClient interface {
	SendMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*ChatMessage, error)
}

type chatExampleClient struct {
	cc *grpc.ClientConn
}

func NewChatExampleClient(cc *grpc.ClientConn) ChatExampleClient {
	return &chatExampleClient{cc}
}

func (c *chatExampleClient) SendMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*ChatMessage, error) {
	out := new(ChatMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatExample/sendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatExampleServer is the server API for ChatExample service.
type ChatExampleServer interface {
	SendMessage(context.Context, *ChatMessage) (*ChatMessage, error)
}

// UnimplementedChatExampleServer can be embedded to have forward compatible implementations.
type UnimplementedChatExampleServer struct {
}

func (*UnimplementedChatExampleServer) SendMessage(ctx context.Context, req *ChatMessage) (*ChatMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterChatExampleServer(s *grpc.Server, srv ChatExampleServer) {
	s.RegisterService(&_ChatExample_serviceDesc, srv)
}

func _ChatExample_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatExampleServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatExample/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatExampleServer).SendMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatExample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatExample",
	HandlerType: (*ChatExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendMessage",
			Handler:    _ChatExample_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatpb/chat.proto",
}
